### ISSUE TITLE
Add new units delimiter - pt_8

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#135]
pt_8 - Eighths of a point (24 eighths of a point = 3 points).
Sometimes this is used for set width of the border

**Comment by ShockwaveNN** [comment]
Example doc, please.

**Comment by flaminestone** [comment]
[SetBetweenBorder.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/438922/SetBetweenBorder.docx)
   expect(docx.elements.first.borders.between.sz).to eq(OoxmlParser::OoxmlSize.new(24, :pt_8))

**Comment by ShockwaveNN** [comment]
Implemented in #150
