### ISSUE TITLE
Add shading type of background_color option for run

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#144]
The shading type applied to the contents of the text run. Need option `nil` and `clear` for background_color option
See examples:
`nil` type
[nil.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/436747/nil.docx)
`clear` type
[clear.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/436748/clear.docx)

**Comment by ShockwaveNN** [comment]
Implemented #149
