### ISSUE TITLE
First page header is not exist in docx obj

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#151]
[RemoveHeader.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/439001/RemoveHeader.docx)
In first page header - 

` "This is page header #1. You will not see it, as it will be removed."`

In second header - 

`"This is page header #2. Only this header can be seen, as the first one has been removed."`

But docx.notes objecT (only one) has one element with second headers data.

**Comment by ShockwaveNN** [comment]
This header stored not in 'notes' section of document, but rather in section of first paragraph. So I'm not sure at now which way is the best to implement parsing of this kind of header.

**Comment by ShockwaveNN** [comment]
It was easier, that I intended. Implemented in #200
