### ISSUE TITLE
Add opportunity to get header and footer distance to top/bottom 

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#154]
FooterDistance = 1440 twips	
[SetFooterDistance.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/439068/SetFooterDistance.docx)

HeaderDistance = 1440 twips	
[SetHeaderDistance (1).docx](https://github.com/ONLYOFFICE/ooxml_parser/files/439072/SetHeaderDistance.1.docx)

**Comment by ShockwaveNN** [comment]
Already implemented
`docx.page_properties.margins.footer`
`docx.page_properties.margins.header`
