### ISSUE TITLE
Delete "units" from .ind property

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#156]
[SetIndFirstLine.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/440758/SetIndFirstLine.docx)
There is `docx.elements.first.ind.units` property, and other property on this lvl is not OoxmlSize object

**Comment by ShockwaveNN** [comment]
Imelemented https://github.com/ONLYOFFICE/ooxml_parser/pull/161
