### ISSUE TITLE
Cell margins is float, not OoxmlSize obj

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#160]
[GetTablePr.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/441936/GetTablePr.docx)
`docx.elements[1].rows.first.cells.first.properties.margins.top.class` - Float
Its true for left, right and bottom margins

**Comment by ShockwaveNN** [comment]
Fixed
See #164
