### ISSUE TITLE
Row height is nil in docx obj

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#162]
[GetTableRowPr.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/441996/GetTableRowPr.docx)
Docx file has table with height row = 1440 twips and with rule from height value is atLeast, but code:
`docx.elements[1].rows.first.table_row_properties.height` return nil

**Comment by ShockwaveNN** [comment]
Implemented
#163
