### ISSUE TITLE
Add table border in docx obj

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#171]
[SetCellBorderBottom.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/444375/SetCellBorderBottom.docx)
`docx.elements[1].properties.table_borders`
In example, table has only row-bottom border, type - single, 32 size(point_8 unit), 0 pt - space and 0, 0, 0, 255 color

**Comment by flaminestone** [comment]
Maybe this property is exist in other object, but i cant find it anywhere

**Comment by ShockwaveNN** [comment]
Implemented #197
