### ISSUE TITLE
Delete merge option

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#172]
[MergeCells.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/444490/MergeCells.docx)
In this example, cells 2.2 -3.3 is merged. 
`docx.elements[1].rows[1].cells[1].properties.merge`

**Comment by ShockwaveNN** [comment]
`merge` is an alias for `grid_span`
So 
`docx.elements[1].rows[1].cells[1].properties.merge` return a `GridSpan` with attribute `value` = 2, I don't see a problem

**Comment by flaminestone** [comment]
Yes, but in debug i see `docx.elements[1].rows[1].cells[1].properties.merge = false`.
![screenshot from 2016-09-02 16-17-38](https://cloud.githubusercontent.com/assets/6047261/18205108/f860dbf8-7128-11e6-9804-05bd061924e4.png)
Its becouce obj contain merge option, and alias is not see in debag.
Maybe replace `merge` to `grid_span` will be correctly?

**Comment by ShockwaveNN** [comment]
Fixed #194
