### ISSUE TITLE
Add type of fill to table shading

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#174]
[SetShd.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/444741/SetShd.docx)
`docx.elements[1].properties.shd` - this option is contains only color (OoxmlParser::Color.new(238, 238, 238)), but not contain type of shading (`clear` in example file)

**Comment by ShockwaveNN** [comment]
Fixed in #196
