### ISSUE TITLE
table_width is parsed like a flout

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#176]
[SetStyle.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/446854/SetStyle.docx)
In example file, table_width is eq` ("percent", 100);. `
But parser is return 8.818342151675486 number.
Need to return Ooxml size parser object with `100%` value.
`docx.elements[1].properties.table_width` is a path

**Comment by ShockwaveNN** [comment]
Implemented in #192
