### ISSUE TITLE
 table_look not content ColBandSize and RowBandSize

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#179]
[SetStyleColBandSize (8).docx](https://github.com/ONLYOFFICE/ooxml_parser/files/447241/SetStyleColBandSize.8.docx)
is a ColBandSize = 2

[SetStyleRowBandSize.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/447244/SetStyleRowBandSize.docx)
is a RowBandSize = 2

[SetStyleColBandSize5.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/447248/SetStyleColBandSize5.docx)
is a ColBandSize = 5

[SetStyleRowBandSize5.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/447250/SetStyleRowBandSize5.docx)
is a RowBandSize = 5

**Comment by ShockwaveNN** [comment]
Custom band sizes implemented in #181 
Default band size can be found in table style, will be accesable after recursive parsing of attributes
