### ISSUE TITLE
table border space is not ooxmlsize obj, if it eq 0

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#180]
[SetTableBorderBottom.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/447333/SetTableBorderBottom.docx)
`docx.elements[1].properties.table_borders.bottom.space` is equal 0:float
Need to eq `OoxmlSize.new(0, :point)`

[SetTableBorderBottom11.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/447428/SetTableBorderBottom11.docx)
space = 11 points in this file

**Comment by ShockwaveNN** [comment]
mplemented in #184
