### ISSUE TITLE
table border space is not ooxmlsize obj, its float

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#182]
[SetTableInd.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/447418/SetTableInd.docx)
`docx.elements[1].properties.table_indent` = 2.5396825396825395 (!):float

**Comment by ShockwaveNN** [comment]
Implemented in #184

**Comment by ShockwaveNN** [comment]
Fixed #186
