### ISSUE TITLE
Add TableLayout to table properties

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#183]
[SetTableLayout (2).docx](https://github.com/ONLYOFFICE/ooxml_parser/files/447489/SetTableLayout.2.docx)
TableLayout =  fixed

[SetTableLayout.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/447490/SetTableLayout.docx)
TableLayout =  autofit

**Comment by ShockwaveNN** [comment]
Implmeneted in #185
