### ISSUE TITLE
Cell fill is nil in docx obj

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#188]
[SetTableLook (2).docx](https://github.com/ONLYOFFICE/ooxml_parser/files/449263/SetTableLook.2.docx)
`docx.elements[1].rows.first.cells.first.properties.fill`

**Comment by ShockwaveNN** [comment]
It parsed in this path:
`docx.elements[1].properties.table_style.table_style_properties_list.first.table_cell_properties.shd`
