### ISSUE TITLE
Numbering properties is eq one(1), cant get properties from obj

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#195]
[GetTextPr.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/454936/GetTextPr.docx)
`docx.elements.first.numbering.numbering_properties.ilvls.first.font` =  "Calibri"
`docx.elements.first.numbering.numbering_properties.ilvls.first.font_size` = 28
but now 
`docx.elements.first.numbering.numbering_properties = 1`

**Comment by ShockwaveNN** [comment]
Incorrect usage. 
Numbering properties looks like this:
```
<w:numPr>
<w:ilvl w:val="0"/>
<w:numId w:val="1"/>
</w:numPr>
```
So, to access real properties of numbering you should call method
`numbering.abstruct_numbering`
Correct is:
`docx.elements.first.numbering.abstruct_numbering.level_list.first.run_properties.font_name`
`docx.elements.first.numbering.abstruct_numbering.level_list.first.run_properties.size.value`
