### ISSUE TITLE
Add separator between numbering and text 

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#220]
[space.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/461258/space.docx)
[tab.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/461259/tab.docx)
[none.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/461285/none.docx)
`docx.elements[0].numbering.abstruct_numbering.level_list.first` - is a numbering style. In first example, after numbering has setted space. In second - tab. In third - none.

**Comment by ShockwaveNN** [comment]
Implemented in #221
