### ISSUE TITLE
'schemeClr' for color properties

### ISSUE THREAD

**Issue by DaftTrick** [ONLYOFFICE/ooxml_parser#222]
[CreateSchemeColor.xlsx](https://github.com/ONLYOFFICE/ooxml_parser/files/463678/CreateSchemeColor.xlsx)
```
<a:gs pos="0">
<a:schemeClr val="accent6"/>
</a:gs>
```
`xlsx.worksheets.first.drawings.first.shape.properties.fill_color.value.gradient_stops.first.color`

**Comment by ShockwaveNN** [comment]
`xlsx.worksheets.first.drawings.first.shape.properties.fill_color.value.gradient_stops.first.color.converted_color.scheme #accent6`
