### ISSUE TITLE
Parent is nil

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#227]
[SetShd.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/463875/SetShd.docx)
`docx.elements[1].properties.table_style.table_cell_properties.color.parent` eq nil

**Comment by ShockwaveNN** [comment]
Fix in #238 
`docx.elements[1].properties.table_style.table_cell_properties.color` now is `nil`
