### ISSUE TITLE
right_to_left value is wrong

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#228]
[SetTextDirection.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/464007/SetTextDirection.docx)
`docx.elements[1].properties.right_to_left` is true, but text in table (elements[1]) is write to up/

**Comment by flaminestone** [comment]
[SetJc.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/469048/SetJc.docx)
In this example, all cells has align :center, but `docx.elements[1].properties.right_to_left` is true.
#issues_228 #gungsta

**Comment by ShockwaveNN** [comment]
Remove parsing `right_to_left` since it was totally wrong.
Need examples of files with this option set (if exists)
