### ISSUE TITLE
Drawing position is float

### ISSUE THREAD

**Issue by DaftTrick** [ONLYOFFICE/ooxml_parser#230]
[SetPosition.xlsx](https://github.com/ONLYOFFICE/ooxml_parser/files/464174/SetPosition.xlsx)
`xlsx.worksheets.first.drawings.first.position.from.column_offset`
Need this to eq OoxmlParser::OoxmlSize.new(72000, :emu)
And also for `xlsx.worksheets.first.drawings.first.position.from.row_offset`

**Comment by ShockwaveNN** [comment]
Fixed #223
