### ISSUE TITLE
xlsx spacing is dimensionless

### ISSUE THREAD

**Issue by DaftTrick** [ONLYOFFICE/ooxml_parser#232]
[SetSpacingAfter.xlsx](https://github.com/ONLYOFFICE/ooxml_parser/files/467162/SetSpacingAfter.xlsx)
`xlsx.worksheets.first.drawings.first.shape.text_body.paragraphs.first.properties.spacing.after`

**Comment by ShockwaveNN** [comment]
Fixed in #235
