### ISSUE TITLE
Add table_height to table properties

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#239]
[SetHeight.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/469714/SetHeight.docx)
In this example, height = 720 twip and type =  "atLeast", but i cant find this properties in ooxml object

**Comment by ShockwaveNN** [comment]
`docx.elements[1].properties.table_style.table_row_properties.height.value`
There is no `atLeast` in styles.xml, so I presume it is defualt value
