### ISSUE TITLE
Align of paragraph, if it set to cell, is wrong

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#241]
[GetParaPr.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/469980/GetParaPr.docx)
`docx.elements[1].rows.first.cells.first.elements.first.align` - this code is return "left", but text in paragraph has align = center

**Comment by ShockwaveNN** [comment]
Implemented in `table_style` in #248
