### ISSUE TITLE
Color of cell is nill

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#242]
[GetTableCellPr.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/470020/GetTableCellPr.docx)
`docx.elements[1].rows.first.cells.first.properties.color` is return nil, bun in document i setted ("clear" type and  0xEE, 0xEE, 0xEE color (238, 238, 238)

**Comment by ShockwaveNN** [comment]
Fixed in #246
