### ISSUE TITLE
Font style of cells test is wrong

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#244]
[GetTextPr.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/470155/GetTextPr.docx)
In first cell of table i see bold text, but ooxml object is not show it. In show text, but font style is wrong
`docx.elements[1].rows.first.cells.first.elements.first.character_style_array[1].font_style.bold`

**Comment by ShockwaveNN** [comment]
`docx.elements[1].properties.table_style.table_style_properties_list.first.run_properties.font_style.bold`
