### ISSUE TITLE
Page break is not parsed

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#247]
[AddPageBreak.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/471572/AddPageBreak.docx)
`docx.elements.first.page_break` is false, but its true

**Comment by ShockwaveNN** [comment]
`docx.elements.first.page_break` is break for DocxParagraph
In your case you're looking for
`docx.elements.first.nonempty_runs.first.break` => `:page`
