### ISSUE TITLE
Spacing is float

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#249]
[SetSpacing.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/471728/SetSpacing.docx)
I set spacing = 80 twips in this example(`docx.elements.first.nonempty_runs[1]`), but 
`docx.elements.first.nonempty_runs[1].spacing` = 0.1
`docx.elements.first.nonempty_runs[1].run_properties.spacing.value` = 80 (not OoxmlSize object)

**Comment by ShockwaveNN** [comment]
Fixed in #259
