### ISSUE TITLE
:twip and :dxa units is not equal

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#262]
[SetTableInd.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/476373/SetTableInd.docx)
`docx..elements[1].properties.table_style.table_properties.table_indent == OoxmlParser::OoxmlSize.new(1400.0, :twip)` - its false
but origin table indent is 1440 twip (:dxa in object)

**Comment by ShockwaveNN** [comment]
Maybe it's a typo in your code?
You mention 
`OoxmlParser::OoxmlSize.new(1400.0, :twip)` but it's actually 1440!
So I tried
`docx.elements[1].properties.table_style.table_properties.table_indent == OoxmlParser::OoxmlSize.new(1440.0, :twip)` and it's good

**Comment by flaminestone** [comment]
@ShockwaveNN , you right, thank you
