### ISSUE TITLE
Add height type to table row properties

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#263]
[SetHeight.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/476788/SetHeight.docx)
I set height 720 dxa, type "atLeast". I see height in `docx.elements[1].properties.table_style.table_row_properties.height.value`
but cant find type

**Comment by ShockwaveNN** [comment]
I need a file with same content, but different from `atLeast` height type

**Comment by flaminestone** [comment]
[SetHeight.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/484586/SetHeight.docx)
height tyle is "auto" in this file

**Comment by ShockwaveNN** [comment]
@flaminestone Is there an option to set it to something different from `auto`
In auto there is just no `docx.elements[1].properties.table_style.table_row_properties` node, it empty.

**Comment by flaminestone** [comment]
@ShockwaveNN no. There are only `auto` and `atLeast` types. I not see anything else

**Comment by ShockwaveNN** [comment]
@flaminestone so, I think you should check if `docx.elements[1].properties.table_style.table_row_properties` node exist - this mean it is `atLeast`
It there is no such node - imply this is `auto`
