### ISSUE TITLE
run_properties is nil after language  seted

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#265]
[SetLanguage.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/476931/SetLanguage.docx)
I have seted language "en-CA", cant find it in `docx.elements.first.character_style_array[1].run_properties`

**Comment by ShockwaveNN** [comment]
Implemented in #280 
This is stored in default document styles
See
`docx.styles.document_defaults.run_properties_default.run_properties.language`
