### ISSUE TITLE
Position and spacing in character_style_array is float

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#266]
[SetPosition.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/476946/SetPosition.docx)
I set position =  10 hps (Half-points, 2 half-points = 1 point), but in object position = 0.2

[SetSpacing.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/477021/SetSpacing.docx)
I set spacing =  80 twips , but in object ` docx.elements.first.character_style_array[1].spacing` = 0.1

**Comment by ShockwaveNN** [comment]
Use 
`docx.styles.document_defaults.run_properties_default.run_properties.position.value`
and 
`docx.styles.document_defaults.run_properties_default.run_properties.spacing.value`
Introduced in #280
