### ISSUE TITLE
Footnote in document is nil, but its wrong

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#284]
[footnote.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/498209/footnote.docx)
I see docx.elements.first.character_style_array in all array elements, and cant find data.

**Comment by flaminestone** [comment]
[note.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/498444/note.docx)
This file with other *note type

**Comment by ShockwaveNN** [comment]
You can find footnote and endnote in 
`docx.elements.first.character_style_array[1].endnote`
`docx.elements.first.character_style_array[1].footnote` accordingly.
Newerless both objects was not recognized by `nonempty_runs`, it will be fixed in #285
