### ISSUE TITLE
Cant change default paragraph style

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#291]
[Document2.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/531970/Document2.docx)
In this document i change normal style(font color). But i cant find it style in docx object.
```
    style_name = docx.document_styles.map { |currert_element| currert_element.name }
    normal_style = docx.document_styles[style_name.index('Normal')]
```
`normal_style` is not contain paragraph properties and other setups

**Comment by ShockwaveNN** [comment]
`docx.document_style_by_name('Normal').run_properties.font_color`
