### ISSUE TITLE
element_by_description method is work uncorrectly

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#293]
[first.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/533332/first.docx)
I tryed to take element by description like this:
`OoxmlParser::DocxParser.parse_docx("path_to_docx_file").element_by_description(location: :canvas, type: :shape)`
But i get element with runs without `alternate_content` object.

I have one shape and one chart in file, and i see its in docx object after parsing, but when i use `element_by_description` method - it objects has hiding

**Comment by ShockwaveNN** [comment]
Yeah, I think name of method `element_by_description` is somehow incorrect.
But it was designed to return `DocxParagraph` object of document, so `element_by_description(location: :canvas, type: :shape)` should return paragraph inside shape, not shape itself.
I may change name of method in future, but not the behavior.
