### ISSUE TITLE
check_effect_transition is work uncorrectly

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#294]
I parse  this file
[Check none - Effect (1).pptx](https://github.com/ONLYOFFICE/ooxml_parser/files/541120/Check.none.-.Effect.1.pptx)
and want to check effect transition:
`pptx.slides.first.check_effect_transition(:none, nil)` - it false, but no effect in pptx file

**Comment by ShockwaveNN** [comment]
Fixed in #295 
Use
`expect(pptx.slides.first.alternate_content.transition.properties).to be_nil`
