### ISSUE TITLE
File Parsing on Windows not working

### ISSUE THREAD

**Issue by maxchill** [ONLYOFFICE/ooxml_parser#302]
I wrote a simple demonstration app, essentially copied from the example page.  The code parses the docx successfully on a Linux box, however the same code on windows seems to choke on all Windows paths.  Looks like the path isn't being accepted by ruby-magic gem or something in encrypted_file method.
Is there a configuration workaround to force treating like an unencrypted file to bypass this?  

```
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ooxml_parser-0.1.2/lib/ooxml_parser/common_parser/common_data/ooxml_document_object.rb:29:in ``': No such file or directory - file "./test.docx" (Errno::ENOENT)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ooxml_parser-0.1.2/lib/ooxml_parser/common_parser/common_data/ooxml_document_object.rb:29:in `encrypted_file?'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ooxml_parser-0.1.2/lib/ooxml_parser/common_parser/parser.rb:7:in `parse'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ooxml_parser-0.1.2/lib/ooxml_parser/docx_parser/docx_parser.rb:7:in `parse_docx'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mygem-0.8.8/exe/doxparser:93:in `block (2 levels) in <top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mygem-0.8.8/exe/doxparser:73:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mygem-0.8.8/exe/doxparser:73:in `block in <top (required)>'
        from C:/Ruby22-x64/lib/ruby/2.2.0/optparse.rb:917:in `initialize'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mygem-0.8.8/exe/doxparser:35:in `new'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mygem-0.8.8/exe/doxparser:35:in `<top (required)>'
        from C:/Ruby22-x64/bin/doxparser:22:in `load'
        from C:/Ruby22-x64/bin/doxparser:22:in `<main>'
```

**Comment by ShockwaveNN** [comment]
@maxchill could you try install gem from master, it should be fixed for some times. 
Add line to your `Gemfile` like this
```
gem 'ooxml_parser', git: 'https://github.com/ONLYOFFICE/ooxml_parser'
```

**Comment by maxchill** [comment]
@ShockwaveNN thanks for quick response.  I had actually attempted using the gem from master before posting, however I some compilation issues with ruby-magic on windows, so posted here instead.

Now I've got the gem built and installed I can confirm the latest version works.

**Comment by ShockwaveNN** [comment]
@maxchill Yeah, it's quite hard to install stuff on windows, but all my spec are work quite well on Windows, so enjoy
