### ISSUE TITLE
Failure opening / extracting word doc when ruby script bundled in Ocra EXE

### ISSUE THREAD

**Issue by maxchill** [ONLYOFFICE/ooxml_parser#304]
Version: ooxml_parser from master.

Parsing a word file is working fine with a ruby script I wrote on Windows.  However, since I'm working on a ruby tool I distribute to other users, I usually generate an EXE version using the ocra gem https://github.com/larsch/ocra.

It seems the temp dir ocra uses, in combination with very long path lengths extracted from Docx file is maxing out the Windows Max Path length of 255.  At least that is my theory.

Perhaps it can be made configurable to write temp files to different directory?

```
FATAL ERROR: Failed to create directory 'C:\Users\maxchill\AppData\Local\Temp\ocrFE86.tmp\lib\ruby\gems\2.2.0\gems\ooxml_parser-0.1.2\lib\ooxml_parser\common_parser\common_data\alternate_content\drawing\graphic\shape\shape_properties\docx_shape_properties\preset_geometry\shape_adjust_value_list'.
```

**Comment by ShockwaveNN** [comment]
Seems that problem not in temp file itself.
Looks like it failed on `bundle install` stage, on extracting gem from gemfile, not on parsing document files itself, am I right?

I'm not an advanced windows user, but as far as I remember - there is a way to remove limitation of 255 symbols in Windows

**Comment by ShockwaveNN** [comment]
On second look - seems that is temp folder created by `ocra`, like in tmp name `ocrFE86` (notice ocr letters), and seems there is a way to configure `ocra` for different tmp path - https://github.com/larsch/ocra/blob/master/bin/ocra#L170

**Comment by maxchill** [comment]
You are right, it was the gem extraction process failing, not the docx extraction.
The `--chdir-first` parameter uses the directory the exe in placed in as extraction location.
`ocra --chdir-first --gem-all=ooxml_parser --no-autoload testapp.rb`

I then placed the exe in a directory c:\tools\test.exe to bypass the path length issues.

Thanks again.
