### ISSUE TITLE
Found phantom chart in file

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#316]
[phantom.xlsx](https://github.com/ONLYOFFICE/ooxml_parser/files/673024/phantom.xlsx)
In xlsx obj. i found chart, but i cant see it in Excel
OoxmlParser::Parser.parse('/home/flamine/phantom.xlsx').worksheets.first.drawings.first.picture.chart

**Comment by ShockwaveNN** [comment]
File have embedded `xlsx`
`Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/package" Target="../embeddings/Microsoft_Excel_Worksheet1.xlsx"/>`
