### ISSUE TITLE
Cant find grideline settings

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#320]
I can hide gridline in sheet, but cant find this setting in xlsx parser object
This is 2 files with gridline show and hide
[hide.xlsx](https://github.com/ONLYOFFICE/ooxml_parser/files/675301/hide.xlsx)
[show.xlsx](https://github.com/ONLYOFFICE/ooxml_parser/files/675302/show.xlsx)

**Comment by ShockwaveNN** [comment]
Implemented in #321
