### ISSUE TITLE
Add review metadata to ooxml_parser object

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#344]
[The opening of the Chat in the Left Sidebar (1).docx](https://github.com/ONLYOFFICE/ooxml_parser/files/734633/The.opening.of.the.Chat.in.the.Left.Sidebar.1.docx)
In this file i have i change from user with name 'Christopher Turk' ad 10 45 am, but i cant find this data (data about name and data of change, and note what this is a realy review data)

**Comment by flaminestone** [comment]
![image](https://cloud.githubusercontent.com/assets/6047261/22363980/4768320e-e47f-11e6-9136-68405bd88abf.png)
do it for Turk, pls

**Comment by ShockwaveNN** [comment]
implemented #345
