### ISSUE TITLE
Cant get background color from shape

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#366]
[shape.docx](https://github.com/ONLYOFFICE/ooxml_parser/files/847496/shape.docx)
OoxmlParser::DocxParser.parse_docx("/home/flamine/shape.docx").elements.first.character_style_array[1].alternate_content.office2010_content.graphic.data.properties.fill_color has only parent

**Comment by flaminestone** [comment]
[shape (1).docx](https://github.com/ONLYOFFICE/ooxml_parser/files/847739/shape.1.docx)
other background color of shape

**Comment by ShockwaveNN** [comment]
Color in second docx should be parsed
In first docx - color is default, there is not enought data in xml file to get default color
