### ISSUE TITLE
Column element is not contains if it created by advanced paste

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#383]
[Advanced Paste.xlsx](https://github.com/ONLYOFFICE/ooxml_parser/files/905456/Advanced.Paste.use.Formula.column.width.xlsx)
In this example, i set width of first and second column equal 10 and 11 em. Thin, i copied cell (`B1`) and paste to `(`C1), but whin i doing it, i set "Formula + column width" option of advanced paste.
After parsing, i found only first and second column in `xlsx.worksheets[0].columns` object.

**Comment by flaminestone** [comment]
[big_column.xlsx](https://github.com/ONLYOFFICE/ooxml_parser/files/905509/big_column.xlsx)
In this example, first and second column has 30 em in width, but in xml object found only first column

**Comment by flaminestone** [comment]
[New Spreadsheet (1).xlsx](https://github.com/ONLYOFFICE/ooxml_parser/files/905541/New.Spreadsheet.1.xlsx)
next example: first and second columt=30 em, third column - 15 ed

**Comment by ShockwaveNN** [comment]
You should check from `from` and `to` properties.
If second and third column have same width - `from` equal 2, `to` equal 3.
Pretty non-straight-forward method, but it is like this in ooxml
