### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by Qj7** [ONLYOFFICE/ooxml_parser#406]
Where i can found some examples of code. I need parse table and images from .docx file with their directly place in fille. Thank you.

**Comment by ShockwaveNN** [comment]
@Qj7 you can find a lot of examples in `spec` folder - https://github.com/ONLYOFFICE/ooxml_parser/tree/master/spec

**Comment by ShockwaveNN** [comment]
Also forgot to mention - if you use IDE (like RubyMine) - you can navigate parsed tree in debugger and find that you want.
