### ISSUE TITLE
Add opportunity to work with multycharts

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#488]
`OoxmlParser::Parser.parse('Multycharts.xlsx').worksheets.first.drawings.first.graphic_frame.graphic_data.count` 
is equal 1, but this worksheet has multychart: column and line. graphic_data must be equal 2
[Multycharts.xlsx](https://github.com/ONLYOFFICE/ooxml_parser/files/2004760/Multycharts.xlsx)

**Comment by flaminestone** [comment]
[OneType.xlsx](https://github.com/ONLYOFFICE/ooxml_parser/files/2004999/OneType.xlsx)
This spreadsheet has one multi-chart: 2 column and 2 line

**Comment by ShockwaveNN** [comment]
Redone parsing charts in https://github.com/ONLYOFFICE/ooxml_parser/pull/489
