### ISSUE TITLE
Add ability to work with pivot tables

### ISSUE THREAD

**Issue by flaminestone** [ONLYOFFICE/ooxml_parser#614]
I need to check pivot tables exists in some files, but pivot tables is looks like generic table in parser object. Can you add ability to work with it?
I attach file with pivot table for example
[PivotTableIssue.xlsx](https://github.com/ONLYOFFICE/ooxml_parser/files/4831164/PivotTableIssue.xlsx)
On sheet 1 - pivot table (A3-A4)
On sheet 1 - generic table (A1-A3)

**Comment by ShockwaveNN** [comment]
Implemented in https://github.com/ONLYOFFICE/ooxml_parser/pull/615
Basic feature is supported, but there is a lot of other parameters in xml, so please create additional issues for some specific params if needed
