### ISSUE TITLE
Error using the xlsx.pivot_cache construct.

### ISSUE THREAD

**Issue by askonev** [ONLYOFFICE/ooxml_parser#616]
I use the code:

```
require 'ooxml_parser'

all_files = Dir['./docfile/*.xlsx']
all_files.each do |file_path|
  xlsx = OoxmlParser::Parser.parse(file_path.to_s)
  if xlsx.pivot_caches != []
    FileUtils.cp(file_path, './doc_whith_pivot_table')
  end
end
```

I get an error in the debug console:

`Couldn't find /tmp/ruby-ooxml-parser20200630-6891-9hq198/xl/https://qtwu1.turbotaxonline.intuit.com/img/clear.gif file on filesystem. Possible problem in original document`

There is a suspicion that this document is broken.

Documents previously converted x2t odt => xlsx

[madhus yesterday update.xlsx](https://github.com/ONLYOFFICE/ooxml_parser/files/4851263/madhus.yesterday.update.xlsx)
ods file 
[madhus yesterday update.zip](https://github.com/ONLYOFFICE/ooxml_parser/files/4851275/madhus.yesterday.update.zip)

**Comment by ShockwaveNN** [comment]
Hi, I need this file to take a look into it

**Comment by askonev** [comment]
> Hi, I need this file to take a look into it

Sorry, already fixed!

**Comment by ShockwaveNN** [comment]
Seems that this warning is actually at least for for 3'rd sheet

Could you remove all other sheets from this file in MS Office, but leave warning, because if I just re-save this file in LibreOffice - warning is gone.

**Comment by askonev** [comment]
> Seems that this warning is actually at least for for 3'rd sheet
> 
> Could you remove all other sheets from this file in MS Office, but leave warning, because if I just re-save this file in LibreOffice - warning is gone.

[madhus yesterday update.xlsx](https://github.com/ONLYOFFICE/ooxml_parser/files/4852639/madhus.yesterday.update.xlsx)

The document had some unreadable content according to excel.

```
A file-level check was performed, followed by file recovery. Some parts of the document could be restored or deleted.
Recovered Records: Sheet Properties from the /xl/workbook.xml Part (BOOK)
Recovered Records: String Properties from the /xl/sharedStrings.xml Part (Lines)
```

**Comment by ShockwaveNN** [comment]
I've removed warning like `Couldn't find /tmp/ruby-ooxml-parser20200630-6891-9hq198/xl/https://qtwu1.turbotaxonline.intuit.com/img/clear.gif file on filesystem. Possible problem in original document`

But I do nothing with checking that this file is broken to Excel (and I'm not sure I can perform same checks as excel)
If this is needed task - please create new issue
