### ISSUE TITLE
Add support of pivot tables

### ISSUE THREAD

**Issue by alinasafonova** [ONLYOFFICE/ooxml_parser#686]
[pivot_table.xlsx](https://github.com/ONLYOFFICE/ooxml_parser/files/5665731/pivot_table.xlsx)
[pivot_no_table.xlsx](https://github.com/ONLYOFFICE/ooxml_parser/files/5665739/pivot_no_table.xlsx)

**Comment by ShockwaveNN** [comment]
Basic support implemented in #688 and some other and released as v0.11.0

May need improvement in some additional fields, since not 100% params are covered
