### ISSUE TITLE
Add parsing of xlsx files protected with password

### ISSUE THREAD

**Issue by alinasafonova** [ONLYOFFICE/ooxml_parser#882]
The problem with parsing such files is that there is no ability to unzip them. 
I've tried archiving tool Ark and console command 'unzip'. Both methods unzip unprotected xlsx files but do not unzip the protected one.

unzip command returns following error:

> End-of-central-directory signature not found.  Either this file is not a zipfile, or it constitutes one disk of a multi-part archive.  In the latter case the central directory and zipfile comment will be found on the last disk(s) of this archive.
>unzip:  cannot find zipfile directory in one of password_protected_111.xlsx or password_protected_111.xlsx.zip, and cannot find password_protected_111.xlsx.ZIP, period.

[password_protected_111.xlsx](https://github.com/ONLYOFFICE/ooxml_parser/files/7785368/password_protected_111.xlsx)

**Comment by ShockwaveNN** [comment]
```
unzip -P 111 password_protected_111.zip
```

Seems failing either

**Comment by ShockwaveNN** [comment]
Have found not a single working method

Asked our dev team - maybe they have some algorithm name or something

**Comment by ShockwaveNN** [comment]
MS have custom encryption algorithm

https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-offcrypto/3c34d72a-1a61-4b52-a893-196f9157f083

**Comment by ShockwaveNN** [comment]
But seems there is tool for that in ruby

https://github.com/woodbusy/ooxml_decrypt
